import Sidebar from '@/components/Sidebar';
import Card from '@/components/Card';
import { bugs, ideas, meetings, tasks, team } from '@/lib/data';
import { ArrowUpRight, CheckCircle2, Circle, Flame, Rocket, Users } from 'lucide-react';

function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{children}</span>}
function Progress({value}:{value:number}){return <div className="h-3 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-slate-950" style={{width:`${value}%`}}/></div>}

export default function Home(){return <main className="min-h-screen bg-mesh lg:pl-72"><Sidebar/><section className="p-5 md:p-8"><header className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><Badge>비공개 팀 워크스페이스</Badge><h1 className="mt-4 text-4xl md:text-6xl font-black tracking-tight">오늘 해야 할 일이<br/>한눈에 보이는 HQ</h1><p className="mt-4 text-slate-500">회의록, 작업, 버그, 아이디어를 한 곳에서 관리하는 HairFlow 팀 운영 대시보드</p></div><button className="rounded-2xl bg-slate-950 px-5 py-4 text-sm font-bold text-white shadow-soft">+ 새 작업 만들기</button></header>

<div className="grid gap-5 md:grid-cols-4"><Card className="md:col-span-2"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-500">MVP 진행률</p><h2 className="mt-2 text-4xl font-black">42%</h2></div><Rocket className="text-slate-300" size={42}/></div><div className="mt-6"><Progress value={42}/></div><p className="mt-4 text-sm text-slate-500">대시보드 → 작업관리 → 회의록 → Supabase 연결 순서로 진행</p></Card>
<Card><p className="text-sm font-bold text-slate-500">이번 Sprint</p><h2 className="mt-2 text-3xl font-black">Sprint 1</h2><p className="mt-3 text-sm text-slate-500">D-5 · HQ v0.1 배포</p></Card>
<Card><p className="text-sm font-bold text-slate-500">긴급 버그</p><h2 className="mt-2 text-3xl font-black">3개</h2><p className="mt-3 text-sm text-slate-500">높음 1 · 중간 1 · 낮음 1</p></Card></div>

<div className="mt-5 grid gap-5 xl:grid-cols-3"><Card className="xl:col-span-2"><div className="mb-5 flex items-center justify-between"><h3 className="text-xl font-black flex items-center gap-2"><Flame size={20}/>오늘 해야 할 일</h3><ArrowUpRight size={18}/></div><div className="space-y-3">{tasks.map((t,i)=><div key={t.title} className="flex flex-col gap-3 rounded-2xl border border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3">{t.status==='완료'?<CheckCircle2 className="text-emerald-500"/>:<Circle className="text-slate-300"/>}<div><p className="font-bold">{t.title}</p><p className="text-sm text-slate-500">{t.owner} · {t.status} · {t.due}</p></div></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${t.priority==='높음'?'bg-red-50 text-red-600':'bg-slate-100 text-slate-600'}`}>{t.priority}</span></div>)}</div></Card>
<Card><h3 className="mb-5 text-xl font-black flex items-center gap-2"><Users size={20}/>팀원별 현황</h3><div className="space-y-5">{team.map(m=><div key={m.name}><div className="mb-2 flex justify-between"><div><p className="font-bold">{m.name}</p><p className="text-xs text-slate-500">{m.role}</p></div><p className="text-sm font-black">{m.tasks}개</p></div><Progress value={m.workload}/></div>)}</div></Card></div>

<div className="mt-5 grid gap-5 lg:grid-cols-3"><Card><h3 className="text-xl font-black mb-4">최근 회의록</h3>{meetings.map(m=><div key={m.title} className="border-b border-slate-100 py-3 last:border-0"><p className="font-bold">{m.title}</p><p className="text-sm text-slate-500">{m.date}</p><p className="mt-1 text-sm text-slate-600">{m.summary}</p></div>)}</Card><Card><h3 className="text-xl font-black mb-4">아이디어</h3><ul className="space-y-3">{ideas.map(i=><li key={i} className="rounded-2xl bg-slate-50 p-3 text-sm font-semibold">💡 {i}</li>)}</ul></Card><Card><h3 className="text-xl font-black mb-4">버그</h3>{bugs.map(b=><div key={b.title} className="mb-3 flex items-center justify-between rounded-2xl bg-slate-50 p-3"><p className="text-sm font-semibold">{b.title}</p><Badge>{b.level}</Badge></div>)}</Card></div>

<div className="mt-5 grid gap-5 lg:grid-cols-5"><Card className="lg:col-span-3"><h3 className="text-xl font-black mb-4">회의록 AI 정리</h3><textarea className="h-40 w-full resize-none rounded-3xl border border-slate-200 bg-slate-50 p-4 outline-none focus:border-slate-950" placeholder="회의 내용을 여기에 붙여넣으면 요약, 결정사항, 할 일, 담당자, 마감일로 정리하는 기능을 붙일 예정입니다."/><button className="mt-4 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">AI로 정리하기</button></Card><Card className="lg:col-span-2"><h3 className="text-xl font-black mb-4">빠른 링크</h3>{['작업관리','스프린트','회의록','제품문서','Supabase 설정'].map(x=><button key={x} className="mb-3 flex w-full justify-between rounded-2xl border border-slate-100 p-4 text-left font-bold hover:bg-slate-50"><span>{x}</span><ArrowUpRight size={18}/></button>)}</Card></div>
</section></main>}
